'use strict';

const MAX_EDICT_BITS = 11;
const NETWORKED_EHANDLE_ENT_ENTRY_MASK = (1 << MAX_EDICT_BITS) - 1;
const NUM_NETWORKED_EHANDLE_SERIAL_NUMBER_BITS = 10;
const NUM_NETWORKED_EHANDLE_BITS = MAX_EDICT_BITS + NUM_NETWORKED_EHANDLE_SERIAL_NUMBER_BITS;

export const MAX_OSPATH = 260
export const MAX_SPLITSCREEN_CLIENTS = 2
export const MAX_PLAYER_NAME_LENGTH = 128
export const SIGNED_GUID_LEN = 32
export const MAX_CUSTOM_FILES = 4
export const SUBSTRING_BITS = 5
export const MAX_USERDATA_BITS = 14
export const MAX_EDICT_BITS
export const NETWORKED_EHANDLE_ENT_ENTRY_MASK
export const NUM_NETWORKED_EHANDLE_SERIAL_NUMBER_BITS
export const NUM_NETWORKED_EHANDLE_BITS
export const INVALID_NETWORKED_EHANDLE_VALUE = (1 << NUM_NETWORKED_EHANDLE_BITS) - 1
